//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by uippc.rc
//
#define IDS_APP_TITLE                   1
#define IDC_UI                          2
#define ID_VCARD                        3
#define ID_VCARD_NICK                   4
#define IDS_JABBER                      101
#define IDR_MENU                        102
#define IDS_WINDOWS                     102
#define IDS_EXIT                        103
#define IDS_HELP                        104
#define IDD_ABOUTBOX                    105
#define IDS_SEND                        107
#define IDD_STATUS                      107
#define IDS_VERSION                     108
#define IDD_DIRECT_PRESENCE             108
#define IDS_REVDATE                     109
#define IDD_EDIT_CONTACT                109
#define IDM_SEND                        110
#define IDD_CONFERENCE                  111
#define IDM_SMILES                      111
#define IDD_ADD_CONTACT                 112
#define IDD_CONFIG_P1                   113
#define IDD_ACCNT1                      113
#define IDC_COMPLETE                    114
#define IDD_ACCNT2                      114
#define IDC_COMPOSING                   115
#define IDD_OPTIONS1                    115
#define IDD_OPTIONS2                    116
#define IDD_OPTIONS3                    117
#define IDD_ACCNT3                      118
#define IDD_OPTIONS4                    119
#define IDI_BOMBUS                      130
#define IDC_STATIC_2                    202
#define IDC_STATIC_3                    203
#define IDC_STATIC_4                    204
#define IDC_E_JID                       1003
#define IDC_E_PASSWORD                  1004
#define IDC_X_SSL                       1005
#define IDC_X_SASL                      1006
#define IDC_X_ZLIB                      1007
#define IDC_X_PLAIN                     1008
#define IDC_E_HOSTIP                    1009
#define IDC_E_RESOURCE                  1010
#define IDC_X_ZLIB2                     1010
#define IDC_E_PORT                      1011
#define IDC_X_SSL_WARNINGS              1012
#define IDC_AREV                        1013
#define IDC_X_NSRV                      1013
#define IDC_AVERSION                    1014
#define IDC_E_PRIORITY                  1015
#define IDC_AVERSION2                   1015
#define IDC_AHW                         1015
#define IDC_X_PRESAVE                   1016
#define IDC_C_STATUS                    1017
#define IDC_C_PRESET                    1018
#define IDC_E_STATUS                    1019
#define IDC_SPIN_PRIORITY               1021
#define IDC_E_NICK                      1023
#define IDC_C_SERVICE                   1024
#define IDC_C_GROUP                     1025
#define IDC_X_SUBSCR                    1026
#define IDC_SAVE                        1028
#define IDC_DELETE                      1029
#define IDC_E_ROOM                      1030
#define IDC_E_SERVER                    1031
#define IDC_C_NICK                      1033
#define IDC_E_HISTSZ                    1034
#define IDC_SPIN_HIST_SZ                1035
#define IDC_C_BOOKMARK                  1036
#define IDC_X_AUTOJOIN                  1037
#define IDC_X_GROUPS                    1041
#define IDC_X_OFFLINES                  1042
#define IDC_X_HISTORY                   1043
#define IDC_X_PRESENCESORT              1043
#define IDC_X_DELIVERY                  1044
#define IDC_X_COMPOSING                 1045
#define IDC_X_SOUNDS                    1046
#define IDC_X_SIP                       1046
#define IDC_X_VIBRA                     1047
#define IDC_X_DIALUP                    1048
#define IDC_SIP1                        1049
#define IDC_X_AUTOCONNECT               1050
#define IDM_JABBER                      32775
#define IDM_JABBER_STREAMINFO           32777
#define IDM_WINDOWS_ROSTER              32782
#define IDM_WINDOWS_LOG                 32783
#define IDM_JABBER_ACCOUNT              32785
#define IDM_JABBER_STATUS               32787
#define ID_JABBER_ADDACONTACT           32788
#define ID_JABBER_TOOLS                 32789
#define ID_TOOLS_SERVICEDISCOVERY       32790
#define ID_JABBER_JOINCONFERENCE        32791
#define ID_TOOLS_FILETRANSFERS          32792
#define ID_JABBER_OPTIONS               32793
#define ID_TOOLS_STREAMINFO             32794
#define ID_TOOLS_MYVCARD                32795
#define ID_Menu                         32796
#define ID_HELP                         32797
#define ID_WINDOWS                      32798
#define ID_JABBER_ACCOUNT2              32799
#define IDM_JABBER_ACCOUNT2             32800
#define IDM_EXIT                        40000
#define IDM_HELP_ABOUT                  40002
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32801
#define _APS_NEXT_CONTROL_VALUE         1051
#define _APS_NEXT_SYMED_VALUE           116
#endif
#endif
